/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrucksRouteImport } from './routes/trucks'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PostRouteImport } from './routes/post'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GitStatusRouteImport } from './routes/git-status'
import { Route as FuelRouteImport } from './routes/fuel'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BoardRouteImport } from './routes/board'
import { Route as AiAgentRouteImport } from './routes/ai-agent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrucksPostRouteImport } from './routes/trucks.post'
import { Route as PostBulkRouteImport } from './routes/post.bulk'
import { Route as ShipmentsIdDocumentsRouteImport } from './routes/shipments.$id.documents'

const TrucksRoute = TrucksRouteImport.update({
  id: '/trucks',
  path: '/trucks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GitStatusRoute = GitStatusRouteImport.update({
  id: '/git-status',
  path: '/git-status',
  getParentRoute: () => rootRouteImport,
} as any)
const FuelRoute = FuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentRoute = AiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrucksPostRoute = TrucksPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => TrucksRoute,
} as any)
const PostBulkRoute = PostBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => PostRoute,
} as any)
const ShipmentsIdDocumentsRoute = ShipmentsIdDocumentsRouteImport.update({
  id: '/shipments/$id/documents',
  path: '/shipments/$id/documents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-agent': typeof AiAgentRoute
  '/board': typeof BoardRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/fuel': typeof FuelRoute
  '/git-status': typeof GitStatusRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/post': typeof PostRouteWithChildren
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/trucks': typeof TrucksRouteWithChildren
  '/post/bulk': typeof PostBulkRoute
  '/trucks/post': typeof TrucksPostRoute
  '/shipments/$id/documents': typeof ShipmentsIdDocumentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-agent': typeof AiAgentRoute
  '/board': typeof BoardRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/fuel': typeof FuelRoute
  '/git-status': typeof GitStatusRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/post': typeof PostRouteWithChildren
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/trucks': typeof TrucksRouteWithChildren
  '/post/bulk': typeof PostBulkRoute
  '/trucks/post': typeof TrucksPostRoute
  '/shipments/$id/documents': typeof ShipmentsIdDocumentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-agent': typeof AiAgentRoute
  '/board': typeof BoardRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/fuel': typeof FuelRoute
  '/git-status': typeof GitStatusRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/post': typeof PostRouteWithChildren
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/trucks': typeof TrucksRouteWithChildren
  '/post/bulk': typeof PostBulkRoute
  '/trucks/post': typeof TrucksPostRoute
  '/shipments/$id/documents': typeof ShipmentsIdDocumentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-agent'
    | '/board'
    | '/dashboard'
    | '/expenses'
    | '/fuel'
    | '/git-status'
    | '/login'
    | '/map'
    | '/onboarding'
    | '/post'
    | '/pricing'
    | '/profile'
    | '/trucks'
    | '/post/bulk'
    | '/trucks/post'
    | '/shipments/$id/documents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-agent'
    | '/board'
    | '/dashboard'
    | '/expenses'
    | '/fuel'
    | '/git-status'
    | '/login'
    | '/map'
    | '/onboarding'
    | '/post'
    | '/pricing'
    | '/profile'
    | '/trucks'
    | '/post/bulk'
    | '/trucks/post'
    | '/shipments/$id/documents'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-agent'
    | '/board'
    | '/dashboard'
    | '/expenses'
    | '/fuel'
    | '/git-status'
    | '/login'
    | '/map'
    | '/onboarding'
    | '/post'
    | '/pricing'
    | '/profile'
    | '/trucks'
    | '/post/bulk'
    | '/trucks/post'
    | '/shipments/$id/documents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiAgentRoute: typeof AiAgentRoute
  BoardRoute: typeof BoardRoute
  DashboardRoute: typeof DashboardRoute
  ExpensesRoute: typeof ExpensesRoute
  FuelRoute: typeof FuelRoute
  GitStatusRoute: typeof GitStatusRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  OnboardingRoute: typeof OnboardingRoute
  PostRoute: typeof PostRouteWithChildren
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  TrucksRoute: typeof TrucksRouteWithChildren
  ShipmentsIdDocumentsRoute: typeof ShipmentsIdDocumentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trucks': {
      id: '/trucks'
      path: '/trucks'
      fullPath: '/trucks'
      preLoaderRoute: typeof TrucksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/git-status': {
      id: '/git-status'
      path: '/git-status'
      fullPath: '/git-status'
      preLoaderRoute: typeof GitStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuel': {
      id: '/fuel'
      path: '/fuel'
      fullPath: '/fuel'
      preLoaderRoute: typeof FuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agent': {
      id: '/ai-agent'
      path: '/ai-agent'
      fullPath: '/ai-agent'
      preLoaderRoute: typeof AiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trucks/post': {
      id: '/trucks/post'
      path: '/post'
      fullPath: '/trucks/post'
      preLoaderRoute: typeof TrucksPostRouteImport
      parentRoute: typeof TrucksRoute
    }
    '/post/bulk': {
      id: '/post/bulk'
      path: '/bulk'
      fullPath: '/post/bulk'
      preLoaderRoute: typeof PostBulkRouteImport
      parentRoute: typeof PostRoute
    }
    '/shipments/$id/documents': {
      id: '/shipments/$id/documents'
      path: '/shipments/$id/documents'
      fullPath: '/shipments/$id/documents'
      preLoaderRoute: typeof ShipmentsIdDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PostRouteChildren {
  PostBulkRoute: typeof PostBulkRoute
}

const PostRouteChildren: PostRouteChildren = {
  PostBulkRoute: PostBulkRoute,
}

const PostRouteWithChildren = PostRoute._addFileChildren(PostRouteChildren)

interface TrucksRouteChildren {
  TrucksPostRoute: typeof TrucksPostRoute
}

const TrucksRouteChildren: TrucksRouteChildren = {
  TrucksPostRoute: TrucksPostRoute,
}

const TrucksRouteWithChildren =
  TrucksRoute._addFileChildren(TrucksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiAgentRoute: AiAgentRoute,
  BoardRoute: BoardRoute,
  DashboardRoute: DashboardRoute,
  ExpensesRoute: ExpensesRoute,
  FuelRoute: FuelRoute,
  GitStatusRoute: GitStatusRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  OnboardingRoute: OnboardingRoute,
  PostRoute: PostRouteWithChildren,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  TrucksRoute: TrucksRouteWithChildren,
  ShipmentsIdDocumentsRoute: ShipmentsIdDocumentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
